spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketDB
    username: root
    password: 1234 #OK THATS BAD I KNOW
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true